"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import PrelineScript from "./_components/PrelineScript";
import { Provider } from "react-redux";
import store from "./rtk/store";
import { ClerkProvider } from "@clerk/nextjs";
const inter = Inter({ subsets: ["latin"] });
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Provider store={store}>
            <Header />
            {children}
            <Footer />
          </Provider>
          <PrelineScript />
        </body>
      </html>
    </ClerkProvider>
  );
}
